server:
  ssl:
    key-store: classpath:keys/springboot.p12
    key-store-password: Kub3rk@t
    key-store-type: pkcs12
    key-alias: springboot
#    key-password: 123456789)
    enabled: true
  port: 8444




